name: Build and Deploy Lambda Container

on:
  push:
    branches:
      - main
    paths:
      - Dockerfile

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1

      - name: Build Docker Image
        run: docker build -t my_lambda_image .

      - name: Push to ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin <your_ecr_url>
          docker tag my_lambda_image:latest <your_ecr_url>/my_lambda_image:latest
          docker push <your_ecr_url>/my_lambda_image:latest

      - name: Update Lambda
        run: |
          aws lambda update-function-code --function-name my_lambda_container --image-uri <your_ecr_url>/my_lambda_image:latest
